"""
Backtesting engine — the core day-by-day simulation loop.

CRITICAL: Trades execute on signal[t+1], NOT signal[t].
This is achieved by df['signal'].shift(1) — look-ahead bias prevention.
Without this, backtests look unrealistically profitable because they use
information that wouldn't be available at trade time.

Supports:
- Long-only mode (default): BUY on signal=+1, SELL on signal=-1
- Long-short mode (allow_short=True): Also opens shorts on signal=-1 when flat
- ATR risk controls: stop losses, trailing stops, circuit breaker
"""

import pandas as pd
import numpy as np

from src.utils.helpers import load_config
from src.utils.logger import get_logger
from .portfolio import Portfolio
from .transaction_costs import TransactionCosts
from .execution_model import ExecutionModel
from .position_sizing import PositionSizer
from .order_manager import OrderManager
from .risk_controls import RiskControls

logger = get_logger(__name__)


class BacktestEngine:
    """
    Event-driven backtester that simulates trading day by day.

    Flow for each trading day:
    1. Read the PREVIOUS day's signal (shifted by 1 to prevent look-ahead bias)
    2. Check risk controls (stop losses, circuit breaker)
    3. Execute trades at today's open price
    4. Apply transaction costs (commission + slippage)
    5. Mark-to-market at today's close price
    6. Record portfolio equity

    Usage:
        engine = BacktestEngine(data=df_with_signals, ticker="AAPL")
        portfolio = engine.run()
        equity_df = portfolio.get_equity_df()
    """

    def __init__(
        self,
        data: pd.DataFrame,
        ticker: str,
        initial_capital: float | None = None,
        commission: float | None = None,
        slippage: float | None = None,
        position_sizing_method: str = "fixed_capital",
        position_sizing_params: dict | None = None,
        allocation: float | None = None,
        allow_short: bool = False,
        use_stops: bool = False,
        atr_multiplier: float = 2.0,
        use_trailing_stop: bool = True,
        use_circuit_breaker: bool = False,
        circuit_breaker_pct: float = -0.03,
        intraday_square_off: bool = False,
        execution: dict | None = None,
    ):
        """
        Args:
            data: DataFrame with OHLCV data and a 'signal' column from a strategy.
                Works with any bar frequency (1m…1D) — signals execute on the
                NEXT bar's open, and risk resets are per session, not per bar.
            intraday_square_off: If True, force-close open positions on the
                last bar of each session (intraday-only strategies).
            ticker: Stock ticker being backtested.
            initial_capital: Starting cash. Defaults to config.yaml value.
            commission: Commission rate. Defaults to config.yaml value.
            slippage: Slippage rate. Defaults to config.yaml value.
            position_sizing_method: 'fixed_capital', 'fixed_shares', or 'kelly'.
            position_sizing_params: Extra params for the position sizer.
            allocation: Capital allocation fraction (0.0-1.0). Overrides config.
            allow_short: Whether to allow short selling.
            use_stops: Enable ATR-based stop losses.
            atr_multiplier: Stop distance in ATR units (1.5=tight, 2.0=standard, 3.0=wide).
            use_trailing_stop: If True, stop follows price in favorable direction.
            use_circuit_breaker: If True, halt trading on large daily losses.
            circuit_breaker_pct: Daily loss threshold (e.g., -0.03 = -3%).
        """
        self.data = data.copy()
        if "signal" not in self.data.columns:
            raise ValueError("Data must contain a 'signal' column generated by a strategy.")

        self.ticker = ticker
        self.allow_short = allow_short
        self.use_stops = use_stops
        self.intraday_square_off = intraday_square_off

        # Load defaults from config, allow overrides
        try:
            config = load_config()
            trading = config.get("trading", {})
            sizing_config = config.get("position_sizing", {})
        except Exception:
            trading = {}
            sizing_config = {}

        capital = initial_capital or trading.get("initial_capital", 10000.0)
        comm = commission if commission is not None else trading.get("commission", 0.001)
        slip = slippage if slippage is not None else trading.get("slippage", 0.0005)

        self.portfolio = Portfolio(capital)
        # Execution realism: explicit config → full model; otherwise legacy
        # flat slippage reproduced through the same ExecutionModel interface.
        if execution:
            self.exec_model = ExecutionModel(
                commission_pct=comm,
                spread_bps=float(execution.get("spread_bps", 0.0)),
                slippage_model=str(execution.get("slippage_model", "fixed")),
                slippage_bps=float(execution.get("slippage_bps", slip * 1e4)),
                vol_coef=float(execution.get("vol_coef", 0.1)),
                impact_bps=float(execution.get("impact_bps", 10.0)),
                max_participation=float(execution.get("max_participation", 1.0)),
                short_margin_pct=float(execution.get("short_margin_pct", 1.0)),
            )
        else:
            self.exec_model = ExecutionModel(
                commission_pct=comm, slippage_model="fixed",
                slippage_bps=slip * 1e4,
            )
        self.tc = self.exec_model
        self.capped_entries = 0
        self.order_manager = OrderManager(self.portfolio, self.tc, allow_short=allow_short)

        # Risk controls
        self.risk = RiskControls(
            atr_multiplier=atr_multiplier,
            use_trailing_stop=use_trailing_stop,
            circuit_breaker_pct=circuit_breaker_pct,
            use_circuit_breaker=use_circuit_breaker,
        )

        # Allocation priority: explicit param > position_sizing_params > config > default
        if allocation is not None:
            alloc = allocation
        elif position_sizing_params and "allocation" in position_sizing_params:
            alloc = position_sizing_params["allocation"]
        else:
            alloc = sizing_config.get("allocation", 0.95)

        sizing_method = position_sizing_method or sizing_config.get("method", "fixed_capital")
        sizing_params = {"allocation": alloc}
        if position_sizing_params:
            sizing_params.update(position_sizing_params)
        self.sizer = PositionSizer(sizing_method, **sizing_params)

    def run(self) -> Portfolio:
        """
        Execute the full backtest simulation.

        Returns:
            Portfolio object containing equity curve, trade history, and final state.
        """
        logger.info(f"{'='*60}")
        logger.info(f"Starting backtest: {self.ticker}")
        logger.info(f"  Capital: ${self.portfolio.initial_capital:,.2f}")
        logger.info(f"  Data points: {len(self.data)}")
        logger.info(f"  Short selling: {'Enabled' if self.allow_short else 'Disabled'}")
        logger.info(f"  ATR Stops: {'Enabled' if self.use_stops else 'Disabled'}")
        logger.info(f"{'='*60}")

        # Sort by date and ensure we have clean data
        self.data["date"] = pd.to_datetime(self.data["date"])
        self.data = self.data.sort_values("date").reset_index(drop=True)

        # Session bookkeeping (timeframe-agnostic):
        # a "session" is a calendar date on the exchange-local clock.
        session_ids = self.data["date"].dt.date
        # True on the last bar of each session (incl. very last bar)
        is_session_end = (session_ids != session_ids.shift(-1)).values

        # ╔══════════════════════════════════════════════════════════╗
        # ║ CRITICAL: shift(1) prevents look-ahead bias!           ║
        # ║ Signal generated at bar T → trade executes at bar T+1  ║
        # ╚══════════════════════════════════════════════════════════╝
        self.data["trade_signal"] = self.data["signal"].shift(1).fillna(0)

        # Pre-compute ATR for stop loss calculations
        atr_series = None
        if self.use_stops:
            atr_series = self.risk.compute_atr(self.data)

        prev_equity = self.portfolio.initial_capital
        prev_session = None

        # ── Scale: pre-extract numpy arrays — iterrows costs ~50µs/row,
        # which murders minute-data × optimizer workloads. Same logic,
        # same event ordering, plain array indexing.
        n_bars = len(self.data)
        cols = self.data.columns
        _dates = self.data["date"].to_numpy()
        _opens = self.data["open"].to_numpy(dtype=float)
        _highs = self.data["high"].to_numpy(dtype=float)
        _lows = self.data["low"].to_numpy(dtype=float)
        _closes = self.data["close"].to_numpy(dtype=float)
        _vols = (
            self.data["volume"].to_numpy(dtype=float)
            if "volume" in cols else np.zeros(n_bars)
        )
        _signals = self.data["trade_signal"].to_numpy()
        _atr = atr_series.to_numpy(dtype=float) if atr_series is not None else None
        _sessions = session_ids.to_numpy()

        # Bar-by-bar simulation (daily or intraday)
        for idx in range(n_bars):
            # New session → reset the per-session circuit breaker
            bar_session = _sessions[idx]
            if prev_session is not None and bar_session != prev_session:
                self.risk.reset_daily()
            prev_session = bar_session

            date = _dates[idx]
            open_price = _opens[idx]
            close_price = _closes[idx]
            signal = _signals[idx]
            row = {
                "open": open_price, "high": _highs[idx], "low": _lows[idx],
                "close": close_price, "volume": _vols[idx],
            }

            current_position = self.portfolio.positions.get(self.ticker, 0)
            current_atr = _atr[idx] if _atr is not None else 0

            # ── Risk Control: Circuit Breaker ──
            if self.use_stops and prev_equity > 0:
                current_equity = self.portfolio.cash + current_position * open_price
                daily_pnl_pct = (current_equity - prev_equity) / prev_equity
                if self.risk.check_circuit_breaker(daily_pnl_pct):
                    # Circuit breaker tripped — skip trading, just mark-to-market
                    self.portfolio.update_equity(date, {self.ticker: close_price})
                    continue

            # ── Risk Control: Stop Loss Check (intrabar-aware, conservative) ──
            # Gap-through-stop fills at the open; intrabar crosses fill at the
            # stop price. Trailing updates happen AFTER the check (no same-bar
            # look-ahead). See RiskControls.check_stop_intrabar().
            stop_triggered = False
            if self.use_stops and self.risk.in_position and current_position != 0:
                stop_triggered, stop_fill = self.risk.check_stop_intrabar(
                    open_price, row["high"], row["low"], current_atr
                )
                if stop_triggered:
                    if current_position > 0:
                        self.order_manager.execute_trade(
                            date, self.ticker, "SELL", current_position, stop_fill, bar=row
                        )
                    elif current_position < 0:
                        self.order_manager.execute_trade(
                            date, self.ticker, "BUY", abs(current_position), stop_fill, bar=row
                        )
                    self.risk.reset()
                    current_position = self.portfolio.positions.get(self.ticker, 0)

            # Execute trades based on yesterday's signal, at today's open
            if not stop_triggered:
                if signal == 1 and current_position <= 0:
                    if current_position < 0:
                        # Cover the short first (exits always fill in full)
                        cover_qty = abs(current_position)
                        self.order_manager.execute_trade(date, self.ticker, "BUY", cover_qty, open_price, bar=row)
                        self.risk.reset()

                    # BUY signal — enter long (liquidity-capped → partial fills)
                    qty = self.sizer.get_quantity(open_price, self.portfolio.cash)
                    qty, capped = self.exec_model.cap_quantity(qty, row)
                    if capped:
                        self.capped_entries += 1
                    if qty > 0:
                        self.order_manager.execute_trade(date, self.ticker, "BUY", qty, open_price, bar=row)
                        if self.use_stops and current_atr > 0:
                            self.risk.on_entry(open_price, current_atr, "long")

                elif signal == -1 and current_position >= 0:
                    if current_position > 0:
                        # SELL signal — exit long position (exits fill in full)
                        self.order_manager.execute_trade(
                            date, self.ticker, "SELL", current_position, open_price, bar=row
                        )
                        self.risk.reset()

                    if self.allow_short and self.portfolio.positions.get(self.ticker, 0) == 0:
                        # Open a short position (liquidity-capped)
                        qty = self.sizer.get_quantity(open_price, self.portfolio.cash)
                        qty, capped = self.exec_model.cap_quantity(qty, row)
                        if capped:
                            self.capped_entries += 1
                        if qty > 0:
                            self.order_manager.execute_trade(
                                date, self.ticker, "SELL", qty, open_price, bar=row
                            )
                            if self.use_stops and current_atr > 0:
                                self.risk.on_entry(open_price, current_atr, "short")

            # ── Intraday square-off: force-flat on the session's last bar ──
            if self.intraday_square_off and is_session_end[idx]:
                pos = self.portfolio.positions.get(self.ticker, 0)
                if pos > 0:
                    self.order_manager.execute_trade(
                        date, self.ticker, "SELL", pos, close_price, bar=row
                    )
                    self.risk.reset()
                elif pos < 0:
                    self.order_manager.execute_trade(
                        date, self.ticker, "BUY", abs(pos), close_price, bar=row
                    )
                    self.risk.reset()

            # End-of-bar mark-to-market
            self.portfolio.update_equity(date, {self.ticker: close_price})

            # Track previous bar equity for circuit breaker
            equity_curve = self.portfolio.equity_curve
            if equity_curve:
                prev_equity = equity_curve[-1]["total_equity"]

        # Log summary
        self._log_summary()
        return self.portfolio

    def _log_summary(self) -> None:
        """Log a summary of the backtest results."""
        equity_df = self.portfolio.get_equity_df()
        if equity_df.empty:
            return

        start_equity = equity_df["total_equity"].iloc[0]
        end_equity = equity_df["total_equity"].iloc[-1]
        total_return = (end_equity / start_equity - 1) * 100
        num_trades = len(self.portfolio.trade_history)

        logger.info(f"{'='*60}")
        logger.info(f"Backtest Complete: {self.ticker}")
        logger.info(f"  Start equity: ${start_equity:,.2f}")
        logger.info(f"  End equity:   ${end_equity:,.2f}")
        logger.info(f"  Total return: {total_return:+.2f}%")
        logger.info(f"  Total trades: {num_trades}")
        logger.info(f"{'='*60}")
