import pandas as pd
import numpy as np
from src.utils.logger import get_logger
from .portfolio import Portfolio
from .transaction_costs import TransactionCosts
from .position_sizing import PositionSizer
from .order_manager import OrderManager

logger = get_logger(__name__)

class BacktestEngine:
    def __init__(self, data: pd.DataFrame, ticker: str, initial_capital: float = 10000.0,
                 commission: float = 0.001, slippage: float = 0.0005):
        self.data = data.copy()
        if 'signal' not in self.data.columns:
            raise ValueError("Data must contain a 'signal' column generated by a strategy.")
            
        self.ticker = ticker
        self.portfolio = Portfolio(initial_capital)
        self.tc = TransactionCosts(commission, slippage)
        self.order_manager = OrderManager(self.portfolio, self.tc)
        self.sizer = PositionSizer('fixed_capital', allocation=0.99)

    def run(self) -> Portfolio:
        logger.info("Starting backtest simulation...")
        
        # Ensure we're sorted by date
        self.data = self.data.sort_values('date').reset_index(drop=True)
        
        # Strategy outputs signal at t. Trade executes at t+1 open.
        self.data['trade_signal'] = self.data['signal'].shift(1).fillna(0)
        
        for index, row in self.data.iterrows():
            date = row['date']
            open_price = row['open']
            close_price = row['close']
            signal = row['trade_signal']
            
            current_position = self.portfolio.positions.get(self.ticker, 0)
            
            # Simple execution logic
            if signal == 1 and current_position == 0:
                # Buy
                qty = self.sizer.get_quantity(open_price, self.portfolio.cash)
                self.order_manager.execute_trade(date, self.ticker, 'BUY', qty, open_price)
                
            elif signal == -1 and current_position > 0:
                # Sell all
                self.order_manager.execute_trade(date, self.ticker, 'SELL', current_position, open_price)
            
            # End of day mark to market
            self.portfolio.update_equity(date, {self.ticker: close_price})
            
        logger.info("Backtest simulation completed.")
        return self.portfolio
