"""
PDF Report Generator for Alpha Engine.

Generates a professional 1-page tear sheet with:
- Strategy name, ticker, date range
- KPI metrics table
- Equity curve chart (embedded as image)
- Trade summary statistics

Uses fpdf2 for lightweight PDF generation (no heavy LaTeX deps).
"""

import os
import io
from datetime import datetime
from typing import Dict, Any, Optional

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend for server use
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from src.utils.logger import get_logger

logger = get_logger(__name__)


def generate_pdf_report(
    equity_df: pd.DataFrame,
    metrics: Dict[str, Any],
    strategy_name: str,
    ticker: str,
    start_date: str,
    end_date: str,
    initial_capital: float,
    trade_history: list,
    benchmark_equity: Optional[pd.Series] = None,
    output_path: str = "reports/alpha_engine_report.pdf",
) -> Optional[str]:
    """
    Generate a professional PDF tear sheet.

    Args:
        equity_df: DataFrame with 'total_equity' column.
        metrics: Dict of computed metrics (CAGR, Sharpe, etc.)
        strategy_name: Display name of the strategy.
        ticker: Asset ticker.
        start_date: Backtest start date.
        end_date: Backtest end date.
        initial_capital: Starting capital.
        trade_history: List of trade dicts.
        benchmark_equity: Optional benchmark equity series.
        output_path: Where to save the PDF.

    Returns:
        Path to the generated PDF, or None on failure.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("fpdf2 not installed. Run: pip install fpdf2")
        return None

    try:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        # ── Generate equity curve chart as PNG ──
        chart_path = _generate_chart(equity_df, benchmark_equity, strategy_name, ticker)

        # ── Build PDF ──
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # ── Header ──
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(0, 180, 160)  # Teal
        pdf.cell(0, 12, "Alpha Engine", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 6, "Quantitative Research & Backtesting Platform", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # Divider
        pdf.set_draw_color(0, 180, 160)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        # ── Strategy Info ──
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, f"{ticker} - {strategy_name}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Period: {start_date} to {end_date}  |  Initial Capital: ${initial_capital:,.0f}  |  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # ── KPI Table ──
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, "Performance Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        _add_metrics_table(pdf, metrics, initial_capital, equity_df)
        pdf.ln(4)

        # ── Equity Curve Chart ──
        if chart_path and os.path.exists(chart_path):
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 7, "Equity Curve", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
            pdf.image(chart_path, x=10, w=190)
            pdf.ln(4)

        # ── Trade Summary ──
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Trade Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        _add_trade_summary(pdf, trade_history, metrics)

        # ── Footer ──
        pdf.ln(6)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 5, "Generated by Alpha Engine | github.com/RintuRifle/alpha-engine", align="C")

        # Save
        pdf.output(output_path)

        # Cleanup chart image
        if chart_path and os.path.exists(chart_path):
            os.remove(chart_path)

        logger.info(f"PDF report saved to: {output_path}")
        return output_path

    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return None


def _generate_chart(
    equity_df: pd.DataFrame,
    benchmark_equity: Optional[pd.Series],
    strategy_name: str,
    ticker: str,
) -> Optional[str]:
    """Generate equity curve chart as a temporary PNG file."""
    try:
        fig, ax = plt.subplots(figsize=(10, 3.5), dpi=150)
        fig.patch.set_facecolor("#1a1a2e")
        ax.set_facecolor("#1a1a2e")

        # Strategy equity
        dates = equity_df.index
        equity = equity_df["total_equity"].values
        ax.plot(dates, equity, color="#00D4AA", linewidth=1.5, label=strategy_name)

        # Benchmark
        if benchmark_equity is not None and len(benchmark_equity) > 0:
            # Align to strategy dates
            bench_aligned = benchmark_equity.reindex(dates).ffill().bfill()
            if len(bench_aligned.dropna()) > 0:
                ax.plot(bench_aligned.index, bench_aligned.values, 
                       color="#FF6B6B", linewidth=1, linestyle="--", alpha=0.7, label="SPY Benchmark")

        ax.set_ylabel("Portfolio Value ($)", color="#aaa", fontsize=9)
        ax.tick_params(colors="#888", labelsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color("#444")
        ax.spines["bottom"].set_color("#444")
        ax.legend(fontsize=8, facecolor="#1a1a2e", edgecolor="#444", labelcolor="#ccc")
        ax.grid(True, alpha=0.15, color="#444")

        # Format x-axis dates
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
        ax.xaxis.set_major_locator(mdates.AutoDateLocator())
        fig.autofmt_xdate(rotation=30)

        chart_path = "reports/_temp_chart.png"
        os.makedirs("reports", exist_ok=True)
        fig.savefig(chart_path, bbox_inches="tight", facecolor=fig.get_facecolor())
        plt.close(fig)
        return chart_path

    except Exception as e:
        logger.warning(f"Chart generation failed: {e}")
        return None


def _add_metrics_table(pdf, metrics: dict, initial_capital: float, equity_df: pd.DataFrame):
    """Add formatted KPI metrics table to the PDF."""
    pdf.set_font("Helvetica", "", 9)

    final_value = equity_df["total_equity"].iloc[-1] if not equity_df.empty else initial_capital
    total_return = ((final_value / initial_capital) - 1) * 100

    kpis = [
        ("CAGR", f"{metrics.get('cagr', 0) * 100:+.2f}%"),
        ("Total Return", f"{total_return:+.2f}%"),
        ("Sharpe Ratio", f"{metrics.get('sharpe_ratio', 0):.3f}"),
        ("Sortino Ratio", f"{metrics.get('sortino_ratio', 0):.3f}"),
        ("Max Drawdown", f"{metrics.get('max_drawdown', 0) * 100:.2f}%"),
        ("Volatility", f"{metrics.get('volatility', 0) * 100:.2f}%"),
        ("Win Rate", f"{metrics.get('win_rate', 0) * 100:.1f}%"),
        ("Total Trades", f"{metrics.get('total_trades', 0)}"),
        ("Final Value", f"${final_value:,.2f}"),
        ("Alpha", f"{metrics.get('alpha', 0) * 100:.3f}%"),
        ("Beta", f"{metrics.get('beta', 0):.3f}"),
        ("VaR (95%)", f"{metrics.get('var_95', 0) * 100:.2f}%"),
    ]

    # 4 columns, 3 rows
    col_width = 47.5
    for i in range(0, len(kpis), 4):
        row = kpis[i:i + 4]
        for label, value in row:
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(120, 120, 120)
            pdf.cell(col_width, 4, label, align="C")
        pdf.ln()
        for label, value in row:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(col_width, 5, value, align="C")
        pdf.ln(4)


def _add_trade_summary(pdf, trade_history: list, metrics: dict):
    """Add trade summary section to the PDF."""
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)

    total_trades = len(trade_history)
    buys = sum(1 for t in trade_history if t.get("action") == "BUY")
    sells = sum(1 for t in trade_history if t.get("action") == "SELL")

    summary_lines = [
        f"Total Trades: {total_trades}  |  Buys: {buys}  |  Sells: {sells}",
        f"Win Rate: {metrics.get('win_rate', 0) * 100:.1f}%  |  Profit Factor: {metrics.get('profit_factor', 0):.2f}  |  Avg Win/Loss: {metrics.get('avg_win_loss_ratio', 0):.2f}",
    ]

    for line in summary_lines:
        pdf.cell(0, 5, line, new_x="LMARGIN", new_y="NEXT")
